version: '3.6'

services:
  firefox:
    image: cslev/webbrowser_docker:latest
    container_name: webbrowser
    ports:
      - target: 5900
        published: 5555
        protocol: 'tcp'
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - './container_data/cache/:/root/.cache:rw'
      - './container_data/mozilla:/root/.mozilla:rw'
      - './container_data/config:/root/.config:rw'
      - './container_data/SSL:/root/SSL:rw'
#      - '/dev/shm:/dev/shm'
    shm_size: '4gb'
    dns:
      - 9.9.9.9
      - 1.1.1.1
    # stdin_open: true #docker run -i
    # tty: true        #docker run -t
    # command: bash
